version: '2.2'
services: 
    firefox:
        image: selenium/node-firefox:3.8.1-francium
        volumes: 
            - /dev/shm:/dev/shm
        depends_on: 
            - hub
        environment: 
            HUB_HOST: hub
    
    chrome:
        image: selenium/node-chrome:3.8.1-francium
        volumes: 
            - /dev/shm:/dev/shm
        depends_on: 
            - hub
        environment: 
            HUB_HOST: hub
    hub:
        image: selenium/hub:3.8.1-francium
        ports: 
            - "4444:4444"
